### ISSUE TITLE
Missing file: covid_icd_for_gnn.csv

### ISSUE THREAD

**Issue by yikuan8** [v1xerunt/STAN#1]
Thank you for the great repo. Would you mind publishing this dataset?

**Comment by v1xerunt** [comment]
Our paper is a pre-print version and is also under reviewing. There are still some issues in our code and paper and we are currently fixing them. After the full paper is published, we will release a sysnthetic dataset (since the original raw dataset includes privacy issues so that I don't have the permission to publish them).

**Comment by yikuan8** [comment]
Thank you for your response. As mentioned in your manuscript, you compared STAN with CovidGNN [9]. May I ask did you approach the authors of CovidGNN to conduct an experiment of long-term prediction or you have the access to Google COVID-19 Aggregated Mobility Research Dataset to build the graphs by yourselves?

**Comment by v1xerunt** [comment]
No, we don't have the access to their dataset. We only use the same model structure with our own data.

**Comment by zhanghonglu** [comment]
Thank you for the great repo. Would you mind  publish  code of the baselines, such as covidGNN(google)

**Comment by v1xerunt** [comment]
> Thank you for the great repo. Would you mind publish code of the baselines, such as covidGNN(google)

Hi, I think covidGNN is a quite regular GNN with multi-hop skip connections. If you want to use this baseline on your own data, I think it would be easier to re-implement it rather than modifying our code since our baseline code is not well organized.

**Comment by ctangam** [comment]
Hello, your paper is very inspiring. May I ask what's the data columns(4 and 5) you are trying to smooth in the Data2Graph.py?
![image](https://user-images.githubusercontent.com/19775588/101270832-f0987c00-37b7-11eb-9256-d845f3c7e9cf.png)

**Comment by v1xerunt** [comment]
> Hello, your paper is very inspiring. May I ask what's the data columns(4 and 5) you are trying to smooth in the Data2Graph.py?
> ![image](https://user-images.githubusercontent.com/19775588/101270832-f0987c00-37b7-11eb-9256-d845f3c7e9cf.png)

Hi, it's the number of ICU bed and site in each location. Because these number significantly varies in different locations, so we need to smooth them to calculate stable edge weights.

**Comment by ctangam** [comment]
Thank you for your response! But why you didn't use the smoothed data in your code below? You used by_state instead of by_state_np

**Comment by v1xerunt** [comment]
That's an error caused by merging different versions of codes. Thank you for pointing it out. We have fixed it.

**Comment by catcatwang** [comment]
Hello, thank you very much for your contribution. When can you publish the dataset?

**Comment by catcatwang** [comment]
> Thank you for the great repo. Would you mind publishing this dataset?



> 谢谢您的回购。您介意发布此数据集吗？

你好，Hello, have you found the data set? Or is the code running successfully? If so, would you mind sharing it? Thank you.
