### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by catcatwang** [v1xerunt/STAN#2]
Hello, can you publish the dataset now?

**Comment by v1xerunt** [comment]
hello, please refer to the 'Data Availability' section in our paper. The COVID-19 statistics data used in this article are provided by Johns Hopkins University (JHU) Coronavirus Resource Center, and they are publicly available at https://github.com/CSSEGISandData/COVID-19. The claims data used in this article are provided by IQVIA, and they will be shared on request to https://www.iqvia.com/solutions/real-world-evidence/real-world-data-and-insights.

**Comment by catcatwang** [comment]
Sorry to disturb you again. I want to ask, covid_ icd_ for_ gnn.csv Can you publish this dataset file?

**Comment by v1xerunt** [comment]
Sorry, this file is exactly the original dataset that contains private patients' claim data. Personally, I don't have the right to share it. I plan to release a synthetic dataset but I'm too occupied currently. Maybe I will work on that later.

**Comment by catcatwang** [comment]
Well, thank you for your efforts
