### ISSUE TITLE
Recreating the California Experiment

### ISSUE THREAD

**Issue by ndelgigante** [v1xerunt/STAN#4]
@v1xerunt I am trying to recreate the California experiment that is presented in your paper for the STAN mode. The one that resulted in this graph:
![image](https://user-images.githubusercontent.com/60302581/120747555-31572080-c4cf-11eb-9df7-3c476d74a295.png)

Is there other factors of the code that were changed to present these results. I changed train_stan to use California, but was unable to produce the same results.

Thank you

**Comment by v1xerunt** [comment]
Hi, thank you for your interests in our research. In the STAN paper, we use additional claims data as input features. However, in this repo, we can only use publicly available JHU stats as the input features. So the feature dimension reduces from 53 to 3, which causes the model to lose much information. Therefore the results won't be exactly the same as the results in the paper. We are still working on adding more public data sources and also a demo website to solve this.
