### ISSUE TITLE
(Question) The model is for an individual state or all states.

### ISSUE THREAD

**Issue by ndelgigante** [v1xerunt/STAN#5]
Hi, I am just trying to understand the purpose of training the model around a singular state(location). Does this act as a root for the rest of the location in graph model to be build around? For example you could predict for Oregon even if you trained it for California.

It seems to me that the model only learns in the context of that particular state. Would this mean to get an fully fleshed out model to predict one would need to run the training for **each** state?
![image](https://user-images.githubusercontent.com/60302581/121749870-6409a600-cad9-11eb-8e89-15ed9284899c.png)

**Comment by v1xerunt** [comment]
Yes. As we reported in the paper, we build separate models for each location.
