### ISSUE TITLE
Including vaccinations in SIR model

### ISSUE THREAD

**Issue by connieksun** [v1xerunt/STAN#6]
Hello! Great paper and code! I'm working on incorporating vaccination data into STAN and want to use modified SIR equations that include vaccination count and efficacy. The ground truth dS/dI/dR values that I pass through include # of vaccinations, but I'm not sure what other changes would need to be made to the model, specifically in the STAN forward() function. Any insights you have would be very much appreciated. Thanks!

**Comment by v1xerunt** [comment]
Hello, if you want to modify or add new differential equations, you can consider modifying the loss functions to include vaccination. The differential equation in current model does not take vaccination into consideration. The vaccination stats can be only used as input features in current model.
