### ISSUE TITLE
ProxyError: None: Max retries exceeded with url: /CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us//05-22-2020.csv (Caused by None)

### ISSUE THREAD

**Issue by Linda-L** [v1xerunt/STAN#7]
GenerateTrainingData().download_jhu_data('2020-05-01', '2020-12-01')
`ProxyError                                Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 GenerateTrainingData().download_jhu_data('2020-05-01', '2020-12-01')

File L:\200-bit\code\20220511_STAN\data_downloader.py:39, in GenerateTrainingData.download_jhu_data(self, start_time, end_time)
     37 def download_jhu_data(self, start_time, end_time):
     38     date_list = pd.date_range(start_time, end_time).strftime("%m-%d-%Y")
---> 39     data = Pool().map(self.download_single_file, date_list)
     40     print('Finish download')
     41     data = [x for x in data if x is not None]

File ~\anaconda3\envs\pytorch\lib\multiprocessing\pool.py:364, in Pool.map(self, func, iterable, chunksize)
    359 def map(self, func, iterable, chunksize=None):
    360     '''
    361     Apply `func` to each element in `iterable`, collecting the results
    362     in a list that is returned.
    363     '''
--> 364     return self._map_async(func, iterable, mapstar, chunksize).get()

File ~\anaconda3\envs\pytorch\lib\multiprocessing\pool.py:768, in ApplyResult.get(self, timeout)
    766     return self._value
    767 else:
--> 768     raise self._value

ProxyError: None: Max retries exceeded with url: /CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us//05-22-2020.csv (Caused by None)`

**Comment by v1xerunt** [comment]
I can't reproduce this on my end. download_jhu_data() works for me. Please check your network connectivity.
