### ISSUE TITLE
Inconsistencies caused by data processing

### ISSUE THREAD

**Issue by xuexun01** [v1xerunt/STAN#9]
When I reproduced your work, I found that your data processing code `GenerateTrainingData.download_jhu_data()` uses forward filling to handle the missing values, such as `recovered` and `active` data. 
```python
data = pd.concat(data, axis=0).ffill(axis=0).fillna(0)
```
This means that states with missing values are incorrectly using the `recovered` and `active` data from the previous state, which causes some errors. For example, the number of `active` cases is much larger than the number of `confirmed` cases in the state of `Washington`.

**Comment by v1xerunt** [comment]
Thank you for identifying this. I've fixed the bug by conducting the ffill within each state.
